### ISSUE TITLE
Epic: Feedback

### ISSUE THREAD

**Issue by xlarsx** [EstefaniaGuardado/Chatte#33]
# Improve README

- [ ] Show install instructions to run this project
- [ ] Add reference to the Bitbucket repository
- [ ] Add a database model definition
- [ ] Add reference to the License used for this project
- [ ] Add some UML diagrams to understand the basic architecture, the initial could be a `Class Diagram`

# Custom Table View Cell

- [ ] `status` is already the name that the system is looking for, those `if` are unnecessary
- [ ] If `awakeFromNib` or `setSelected:animated:` doesn't bring any value, please remove them

# General Practices

- [ ] Hide in a [category](https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/ProgrammingWithObjectiveC/CustomizingExistingClasses/CustomizingExistingClasses.html) `internal properties`
- [ ] Avoid commented code
- [ ] Try to homologate iteration, or use `enumerates` or simple control flow statements like `for` or define when is used one or the other
- [ ] Free memory in the method `didReceiveMemoryWarning` or if not required, just remove it
- [ ] `Dependency injection` must be only in the `Assembly` for example: `[self.chatBusinessController setHandler: self];`
- [ ] The `registerNibs` method can be extracted as a `Helper function` or in a `Class` that `ChatTableViewController` and `RosterViewController` inherits
- [ ] `numberOfSectionsInTableView` override is superflouos if equal to the response the superclass `UITableViewController`
- [ ] Order the methods from a class based on the functionality or put together methods that belong to a certain `protocol` using [#pragma](http://nshipster.com/pragma/) or split in different `categories`
- [ ] Avoid comments in other language than English
- [ ] As a general rule, 3 nested bucle control flows is a bad sign of code that can be improved ( see: `UpdateValuesHandler` )
- [ ] Only expose the used methods for a given class, for example: `MainAssembly`

# Tips

- [ ] [Improve logging](https://code.tutsplus.com/tutorials/quick-tip-customize-nslog-for-easier-debugging--mobile-19066)
- [ ] Add some documentation for the methods at the protocols this helps a lot with readability

**Comment by xlarsx** [comment]
Iterate: http://stackoverflow.com/questions/992901/how-do-i-iterate-over-an-nsarray
